# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: cekisswg/swg-build:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Move cloned repo (enhancement req to actions/checkout)
        run: mv src-${{ github.run_id }}-${{ github.run_number }} /home/swg/swg-main/src
      - name: Run ANT Build
        run: |
          cd /home/swg/swg-main/src
          ant build_src
          
