# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  container:
    runs-on: ubuntu-latest
    container: cekisswg/swg-build:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - run: cd src
        name: Change to the new dir
      - run: ant build_src
        name: Run ANT build
